# Generated by Django 5.0.7 on 2024-07-17 07:04

import django.db.models.deletion
import issue_tracker.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0002_remove_task_type_typetask_task_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, validators=[issue_tracker.validators.project_title_validator], verbose_name='Title')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, validators=[issue_tracker.validators.project_description_validator], verbose_name='Description')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True, validators=[issue_tracker.validators.description_validator], verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='summary',
            field=models.CharField(max_length=200, validators=[issue_tracker.validators.summary_validator], verbose_name='Summary'),
        ),
        migrations.AddField(
            model_name='task',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='issue_tracker.type', verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='issue_tracker.project', verbose_name='Project'),
        ),
        migrations.DeleteModel(
            name='TypeTask',
        ),
    ]
