# Generated by Django 5.0.7 on 2024-07-18 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0003_project_alter_task_description_alter_task_summary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='task',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Is Deleted'),
        ),
    ]
